author: RABE_IT Services
author_url: https://berndrabe.de
github_url: https://github.com/HHuckebein/ISO3166-1-Alpha2.git
copyright: '© 2016-2021 [RABE_IT Services](https://berndrabe.de) under [open source license](https://github.com/HHuckebein/ISO3166-1-Alpha2/blob/master/LICENSE.txt).'
clean: true